#!/bin/bash
jupyter serverextension enable panel.io.jupyter_server_extension
cd examples
anaconda-project prepare
cd data
wget -q https://s3.eu-west-1.amazonaws.com/assets.holoviews.org/data/earthquakes-projected.parq
cd ../..
