{% set sdata = load_setup_py_data() %}

package:
  name: pyviz
  version: {{ sdata['version'] }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - pyviz = pyviz.cmd:main

extra:
  channels:
    - pyviz

requirements:
  build:
    - python
    - param >=1.7.0
    - numpy
    - setuptools
  run:
    # 
    # Versions for pyviz-maintained packages pinned to ensure mutual compatibility
    # 
    - bokeh 0.13.0
    - holoviews 1.10.7
    - hvplot 0.2.1
    - geoviews 1.5.2
    - datashader 0.6.7
    - param 1.7.0
    - paramnb 2.0.4
    - parambokeh 0.2.3
    # 
    # Direct dependencies for package installation
    # 
    - yaml
    - requests
    # 
    # Direct dependencies of most or all the tutorials
    # 
    - python >=3.6,<3.7 # Pinned in case of unknown future or past compatibility issues
    - ipython 5         # Pinned to avoid tab-completion issue in ipython=6
    - numpy
    - notebook >=5.4    # Pinned to avoid rate limiting for large images with notebook=5.0
    - dask 0.18.1       # Pinned for datashader compatibility
    - jupyter
    - pandas
    - xarray
    # 
    # Directly imported dependencies of certain specialized tutorials
    # 
    - networkx         # Required for some graph examples
    - cartopy          # Required for some GeoViews examples
    - streamz 0.3.0    # Pinned due to StreamingDataFrame name change in 0.3.0
    - scikit-image     # Required for datashader graphs
    - geopandas        # Required for geo data examples
    # 
    # Indirect dependencies of our direct dependencies
    # 
    - selenium          # Required for exporting Bokeh plots to PNG
    - phantomjs         # Required for exporting Bokeh plots to PNG
    - netcdf4           # Required for reading .nc files
    - fastparquet       # Required for reading Parquet files
    - python-snappy     # Required for reading snappy-compressed Parquet files
    - pytest >=3.2      # Required by? Pinned to avoid installation problems on Windows with 3.1?
    - ipywidgets 7      # Required for paramnb. Pinned to avoid JS errors for widgets
    - cffi              # Unstated dependency of fastparquet?
    - tornado 4.5.3     # Required for Jupyter notebook and bokeh server

test:
  imports:
    - pyviz
  commands:
    - pyviz --install-examples pyviz-tutorial

about:
  home: pyviz.org
  summary: How to solve visualization problems with Python tools
  license: BSD 3-Clause
