package:
  name: pyviz
  version: 0.9.2

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

extra:
  channels:
    - pyviz

requirements:
  build:
    - python
    - param
    - numpy
    - setuptools
  run:
    # 
    # Versions for pyviz-maintained packages pinned to ensure mutual compatibility
    # 
    - bokeh 0.12.14
    - holoviews 1.9.5
    - geoviews 1.4.3
    - datashader 0.6.5
    - param 1.5.1
    - paramnb 2.0.3
    - parambokeh 0.2.2
    # 
    # Direct dependencies for package installation
    # 
    - yaml
    - requests
    # 
    # Direct dependencies of most or all the tutorials
    # 
    - python >=3.6,<3.7 # Pinned in case of unknown future or past compatibility issues
    - ipython 5         # Pinned to avoid tab-completion issue in ipython=6
    - numpy 1.13        # Pinned to avoid warnings with numpy=1.14 and bokeh=1.12.14
    - notebook >=5.1    # Pinned to avoid rate limiting for large images with notebook=5.0
    - dask 0.15.4       # Pinned in case of future API changes
    - jupyter
    - pandas
    - xarray
    # 
    # Directly imported dependencies of certain specialized tutorials
    # 
    - networkx         # Required for some graph examples
    - cartopy          # Required for some GeoViews examples
    - streamz=0.2.0    # Pinned due to StreamingDataFrame name change in 0.3.0 
    - scikit-image     # Required for datashader graphs
    - geopandas        # Required for geo data examples
    # 
    # Indirect dependencies of our direct dependencies
    # 
    - selenium          # Required for exporting Bokeh plots to PNG
    - phantomjs         # Required for exporting Bokeh plots to PNG
    - netcdf4           # Required for reading .nc files
    - fastparquet       # Required for reading Parquet files
    - python-snappy     # Required for reading snappy-compressed Parquet files
    - pytest >=3.2      # Required by? Pinned to avoid installation problems on Windows with 3.1?
    - ipywidgets >=6,<7 # Required for paramnb. Pinned to avoid widgets scrolling for hover text.
    - cffi              # Unstated dependency of fastparquet?

test:
  imports:
    - pyviz

about:
  home: pyviz.org
  summary: How to solve visualization problems with Python tools
  license: BSD 3-Clause
