name: docs

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+a[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+b[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+rc[0-9]+"
  workflow_dispatch:
    inputs:
      target:
        description: "Site to build and deploy"
        type: choice
        options:
          - dev
          - main
          - dryrun
        required: true
        default: dryrun
  schedule:
    - cron: "0 2 1 */2 SUN" # every two months on Sunday at 2 am

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  pre_commit:
    name: pre-commit
    runs-on: "ubuntu-latest"
    steps:
      - uses: holoviz-dev/holoviz_tasks/pre-commit@1a9884850782b0b80ba2e91b573e7d63d9d3c3dc # v1.0.1

  build_docs:
    name: Documentation
    needs: [pre_commit]
    runs-on: "ubuntu-latest"
    timeout-minutes: 120
    env:
      MPLBACKEND: "Agg"
      MOZ_HEADLESS: 1
      DISPLAY: ":99.0"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: "eu-west-1"
    steps:
      - name: Install humor sans fonts for XKCD Matplotlib plots
        run: |
          sudo apt-get update -y  &&  sudo apt-get install -y fonts-humor-sans fonts-comic-neue ttf-mscorefonts-installer
          mkdir -p ~/.local/share/fonts
          wget -nc https://github.com/ipython/xkcd-font/blob/master/xkcd-script/font/xkcd-script.ttf?raw=true -O ~/.local/share/fonts/xkcd-Script.ttf || true
          sudo fc-cache -f -v
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: "100"
          persist-credentials: false
      - name: Fetch unshallow
        run: git fetch --prune --tags --unshallow -f
      - name: Set output
        id: vars
        run: |
          echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
          echo "fdatetime=$(date +%Y%m%d-%H%M)" >> $GITHUB_OUTPUT
      - uses: prefix-dev/setup-pixi@5185adfbffb4bd703da3010310260805d89ebb11 # v0.9.6
        with:
          working-directory: examples/
      - name: prepare
        run: pixi run prepare
      - name: generate rst
        run: pixi run doc-rst
      - name: build docs
        run: pixi run doc-build
      - name: git status
        run: |
          git status
          git diff
      - name: Deploy dev
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'dev') ||
          (github.event_name == 'push' && (contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        with:
          personal_token: ${{ secrets.ACCESS_TOKEN }}
          external_repository: holoviz-dev/holoviz
          publish_dir: ./builtdocs
          force_orphan: true
      - name: Deploy main
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
          (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        uses: peaceiris/actions-gh-pages@84c30a85c19949d7eee79c4ff27748b70285e453 # v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./builtdocs
          cname: holoviz.org
          force_orphan: true
      # Upload the tutorial
      - name: git clean
        run: git clean -fxd .
      - name: zip tutorial
        run: cd examples && zip -r ../holoviz_tutorial.zip . -x "data/*"
      - name: save old
        env:
          FDATETIME: ${{ steps.vars.outputs.fdatetime }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: cp holoviz_tutorial.zip holoviz_tutorial_"$FDATETIME"_"$TAG".zip
      - name: Upload tutorial
        if: github.event_name == 'workflow_dispatch' || github.event_name == 'push'
        env:
          FDATETIME: ${{ steps.vars.outputs.fdatetime }}
          TAG: ${{ steps.vars.outputs.tag }}
        run: aws s3 cp ./holoviz_tutorial_"$FDATETIME"_"$TAG".zip s3://assets.holoviz.org/holoviz/tutorial/
      - name: Upload tutorial
        if: |
          (github.event_name == 'workflow_dispatch' && github.event.inputs.target == 'main') ||
          (github.event_name == 'push' && !(contains(steps.vars.outputs.tag, 'a') || contains(steps.vars.outputs.tag, 'b') || contains(steps.vars.outputs.tag, 'rc')))
        run: aws s3 cp ./holoviz_tutorial.zip s3://assets.holoviz.org/holoviz/tutorial/
